### ISSUE TITLE
Clean the Arduino code and add comments

### ISSUE THREAD

**Issue by adithyaanilkumar** [adithyaanilkumar/ZeW-IT#5]
The Arduino code written is not clean. It requires addition of comments and modularization. The task is to add more comments and modularize the components into different functions.

**Comment by JayFiDev** [comment]
I would like to work on this today!

**Comment by js899** [comment]
i'd like to work on this i have experience with arduino, line follower robots and iot home automation...can you assign this to me ??

**Comment by adithyaanilkumar** [comment]
@JayFiDev Thank you for your interest in contributing to ZeW-IT. You can work on the issue. Please do join our IRC channel to stay updated on the project and clear your doubts. The link is updated in the Project Readme.

**Comment by adithyaanilkumar** [comment]
@js899 Im sorry but @JayFiDev  has asked to work on this issue first. If you have experience with Arduino , i will open up a new issue to improve the Arduino code with new feature.

**Comment by js899** [comment]
okay @adithyaanilkumar

**Comment by JayFiDev** [comment]
@js899 i made a pull-request, maybe you want to work further on it when it is merged.

**Comment by js899** [comment]
Sure @JayFiDev

**Comment by js899** [comment]
@adithyaanilkumar I think there's not much left to do the code is nicely modularised and clean, with comments. @JayFiDev might have done good work

**Comment by adithyaanilkumar** [comment]
@js899 Please checkout #10

**Comment by js899** [comment]
> @js899 Please checkout #10
I'm going to be busy for an hour for workout, I'll check after that.
